version: '2.2'
services:
  maven:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${DOCKER_MAVEN_EXTERNAL_PORT-8080}:8080
    command: ['./mvnw', 'spring-boot:run', '-Dspring.devtools.livereload.enabled=true']
    working_dir: /var/www/
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - .:/var/www/
    links:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - mysql:/var/lib/mysql
      - .mysql-database-test.sql:/docker-entrypoint-initdb.d/mysql-database-test.sql
    environment:
      MYSQL_DATABASE: sis
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

volumes:
  mysql:
    driver: local
