version: '2.2'
services:
  maven:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${DOCKER_MAVEN_EXTERNAL_PORT-8080}:8080
    volumes:
      - .:/var/www/

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - mysqldata:/var/lib/mysql
      - .mysql-database-test.sql:/docker-entrypoint-initdb.d/mysql-database-test.sql
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - ${DOCKER_MYSQL_EXTERNAL_PORT-3309}:3306
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

volumes:
  mysqldata:
    driver: local
